# Generated by Django 3.2 on 2024-02-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일 주소')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='이름')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('login_date', models.DateTimeField(auto_now=True, verbose_name='최근 로그인')),
                ('followings', models.ManyToManyField(related_name='followers', to='accounts.User')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'ordering': ['id'],
            },
        ),
    ]
